<?php
/*
 * Copyright © 2015-2024, loufa - All Right Reserved
 */

class EXPORT_STRINGS {
	static public $defaults = array(
		// GENERICS
		'GENERIC_OK',
		'GENERIC_YES',
		'GENERIC_NO',
		'GENERIC_CANCEL',
		'GENERIC_CHANGE',
		'GENERIC_REMOVE',
		'GENERIC_CONFIRM',
		'GENERIC_WARNING',
		'GENERIC_ERROR',
		'GENERIC_ACCEPT_BEGIN',
		'GENERIC_FREE',
        'GENERIC_OTHER',
		'GENERIC_WITH',
		'GENERIC_SENT',
		'GENERIC_INFO',
		'GENERIC_VIRTUAL',
		'GENERIC_SUCCESS',

		// MESSAGE
		'MESSAGE_CONFIRM_DELETE',
		'MESSAGE_SHORT_TERMS_AND_CONDITIONS_BEFORE',
		'MESSAGE_SHORT_TERMS_AND_CONDITIONS_LINK',
		'MESSAGE_SHORT_TERMS_AND_CONDITIONS_AFTER',
		'MESSAGE_ONLINE_FEES',
		'MESSAGE_ENTER_CODE',
		'MESSAGE_CODE_VALIDATING',
		'MESSAGE_CODE_VALIDATED',
		'MESSAGE_CODE_NOT_FOUND',
		'ORDER_PACK6_INSUFFICIENT_TITLE',
		'ORDER_PACK6_INSUFFICIENT_BODY',
		'MESSAGE_SELECTION_NOT_VISITED',
		'MESSAGE_NEED_4_CHECKS',
		'MESSAGE_MISSING_BACKGROUND',
		'MESSAGE_UNSUPPORTED_CC',
		'MESSAGE_PAYMENT_FAILED',
		'MESSAGE_PAYMENT_DECLINED',
		'CODE_REQUEST_MESSAGE_NEED',
		'MESSAGE_PAYMENT_ALREADY_MADE',
		'ORDERAPP_CLEAR_SESSION_CONFIRM',
		// Phase 2
		'ORDERAPP_ERROR_SUBJECT_CODE_ADDED',
		'ORDERAPP_ERROR_ADD_SUBJECT_CODE',
		'ORDERAPP_ERROR_TOUCHUP_NO_PRODUCTS',
		'ORDERAPP_ERROR_TOUCHUP_PHOTO_NOT_IN_PRODUCTS',
		'ORDERAPP_ERROR_TOUCHUP_REVIEW_PHOTO_NOT_IN_PRODUCTS',
		'ORDERAPP_MESSAGE_RELOAD_STATE',
		'ORDERAPP_ADD_TO_CART',
		'ORDERAPP_CANCEL_REMOVAL',
		'ORDERAPP_REMOVE_CART_ITEM',
		'ORDERAPP_EDIT_CART_ITEM',
		'ORDERAPP_MESSAGE_UNIQUE_SESSION',
		'ORDERAPP_ERROR_SESSION_PRODUCTS',
		'ORDERAPP_SUBJECT_NAME_NOTFOUND',
		'ORDERAPP_SUBJECT_NAME_ERROR',
		'ORDERAPP_SUBJECT_NAME_SEARCHING',
		'ORDERAPP_ERROR_CANT_REMOVE_PHOTO',
		'ORDER_COMPLETE_UPDATE',
		'ORDERAPP_MESSAGE_IMG_BACK_COMB_EXIST',
		'ORDERAPP_MESSAGE_NO_PHOTOS',
		'ORDERAPP_MESSAGE_IMG_EXIST',
		'ORDERAPP_MESSAGE_RESET_SESSION',
		'ORDER_COMPLETE_PROMO_NOT_FOUND',
		'ORDER_COMPLETE_PROMO_APPLIED',
		'ORDERAPP_DIGITAL_COPY',
		'ORDERAPP_TOUCHUPS',
		'ORDERAPP_TOUCHUP_CHOSEN',
		'ORDERAPP_CHOOSE_THEME',
		'ORDERAPP_TOUCHUP',
		'ORDERAPP_DIGITAL',
		'ORDERAPP_MESSAGE_ONLY_GROUP_NOT_ALLOWED',
		'ORDERAPP_MESSAGE_ONLY_GROUP_ALLOWED',
		'ORDERAPP_ADD_TO_CART_DIGITAL_DISCOUNT_OVERLAP_OPTION',
        'ORDERAPP_ADD_TO_CART_DIGITAL_DISCOUNT_AMOUNT',
        'ORDERAPP_ADD_TO_CART_ELIGIBLE_DISCOUNT',
        'ORDERAPP_MESSAGE_NO_PHOTOS_SELECTED',
        'ERROR_STRIPE_LOAD_ELEMENT',
        'ERROR_STRIPE_PAYMENT_FAILED',

		// TUTORIALS
		'ORDER_CHOOSE_TUTORIAL_ADD_PHOTO',
		'ORDER_CHOOSE_TUTORIAL_FAV_PHOTO',
		'ORDER_CHOOSE_TUTORIAL_FAV_PANEL',
		'ORDER_CHOOSE_TUTORIAL_HAS_GREENSCREEN',
		'ORDER_CHOOSE_TUTORIAL_NO_GREENSCREEN',
		'ORDER_OVERVIEW_TUTORIAL_SCROLL',
		'ORDER_OVERVIEW_TUTORIAL_CONTACT_INFO',
		'ORDER_OVERVIEW_TUTORIAL_CALCULATE_SHIPPING',
		'ORDER_OVERVIEW_TUTORIAL_CHOOSE_SHIPPING',
		'ORDER_OVERVIEW_TUTORIAL_COMPLETED',
		'ORDER_OVERVIEW_TUTORIAL_INCOMPLETE',
		'ORDER_OVERVIEW_CART_EMPTY',

		// ERRORS
		'ERROR_TITLE',
		'ERROR_SERVER_COMM_FAILED',
		'ERROR_VALIDATE_CONTACT',
		'ERROR_PAYMENT_SERVER_FAILED',
		'ERROR_PASSWORD',
		'ERROR_PASSWORD_MISMATCH',
		'ERROR_SUBJECT_CODE_OWNED',
		'ERROR_SESSION_NOT_FOUND',
		'ERROR_SERVER',
		'ERROR_SERVER_UNKNOWN',

		// VARIABLES
		'VAR_BUSINESS_HOURS'

	);

	static public $admin = array();
}
